stages:
    - build

variables:
    STACK_ROOT: '$CI_PROJECT_DIR/.stack'

job1:
  stage: build
  image: registry.gitlab.com/kaisforza/dotacleave
  artifacts:
    paths:
      - .stack-work/install/
  script:
    - hlint src/ lib/
    - stack --nix build
    - stack --nix exec dotaCleave
  tags:
    - shared
