stages:
    - build

variables:
    STACK_ROOT: '$CI_PROJECT_DIR/.stack'
    STACK_JOBS: '4'

job0:
    stage: build
    artifacts:
        paths:
            - .stack-work/install/
    script:
        - stack --jobs $STACK_JOBS setup
        - stack --jobs $STACK_JOBS install hlint
        - stack --jobs $STACK_JOBS exec hlint .
        - stack --jobs $STACK_JOBS build
        - stack --jobs $STACK_JOBS exec dotaCleave
    tags:
        - haskell
        - stack
